# Generated by Django 4.2.6 on 2023-11-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Feature',
        ),
    ]
