# Generated by Django 4.2.6 on 2023-11-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_productreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id', 'name', 'price')},
        ),
    ]
