# Generated by Django 4.2.6 on 2023-11-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
    ]
